# Generated by Django 3.1a1 on 2020-06-13 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainfile',
            options={'get_latest_by': 'uploaded_at'},
        ),
        migrations.AddField(
            model_name='datamodel',
            name='subscriptions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None),
        ),
    ]
