# Generated by Django 2.2.13 on 2020-06-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoencodermodel',
            name='datamodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoencoder', to='datamodel.DataModel'),
        ),
        migrations.AlterField(
            model_name='pcamahalanobismodel',
            name='datamodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
    ]
