# Generated by Django 2.2.13 on 2020-06-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20200609_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoencodermodel',
            name='datamodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
        migrations.AlterField(
            model_name='gaussiandistributionmodel',
            name='datamodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
        migrations.AlterField(
            model_name='isolationforestmodel',
            name='datamodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
        migrations.AlterField(
            model_name='kmeansmodel',
            name='datamodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
        migrations.AlterField(
            model_name='knnmodel',
            name='datamodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
        migrations.AlterField(
            model_name='localoutlierfactormodel',
            name='datamodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
        migrations.AlterField(
            model_name='oneclasssvmmodel',
            name='datamodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
        migrations.AlterField(
            model_name='pcamahalanobismodel',
            name='datamodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datamodel.DataModel'),
        ),
    ]
